In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('cleaner.csv')

In [3]:
df.head()

Unnamed: 0                       Consumer_complaint_narrative  \
0           0  natual person living human right usc equifa go...   
1           1  submitting complaint delete following fraudule...   
2           2  last year attempted numerous occasion informat...   
3           3  recently made aware     violating consumer rep...   
4           4                                       credit going   

                                             Product  
0  Credit reporting, credit repair services, or o...  
1  Credit reporting, credit repair services, or o...  
2  Credit reporting, credit repair services, or o...  
3  Credit reporting, credit repair services, or o...  
4  Credit reporting, credit repair services, or o...

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df['Consumer_complaint_narrative'],df['Product'],test_size=0.3,random_state=68)

In [7]:
from sklearn.pipeline import Pipeline

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
vectorizer=TfidfVectorizer()

In [10]:
X_train=X_train.astype(str)

In [11]:
text=Pipeline([('tfidf',TfidfVectorizer()),('classifier',RandomForestClassifier(n_estimators=100))])

In [12]:
text.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier())])

In [13]:
predictions=text.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix,classification_report

In [15]:
print(confusion_matrix(y_test,predictions))

[[144  17   2   2 113   2  16   1   7]
 [  8 192  11   4  29   0  52   1  15]
 [  1   9 242  32   2   5  18   6  15]
 [  2   7  34 216   3   2  48   5  16]
 [  6   4   1   3 551   2   5   0   4]
 [  3   0   0   3   4 220  44   5   2]
 [  3   5   4   9   9   0 871   6  15]
 [  0   0   3   1   1   0  17 542   9]
 [  0   1   5   9   3   1  38   7 505]]


In [16]:
print(classification_report(y_test,predictions))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.86      0.47      0.61       304
                                                 Credit card or prepaid card       0.82      0.62      0.70       312
Credit reporting, credit repair services, or other personal consumer reports       0.80      0.73      0.77       330
                                                             Debt collection       0.77      0.65      0.71       333
                          Money transfer, virtual currency, or money service       0.77      0.96      0.85       576
                                                                    Mortgage       0.95      0.78      0.86       281
                                   Payday loan, title loan, or personal loan       0.79      0.94      0.86       922
                                                       

In [17]:
from sklearn import metrics

In [18]:
metrics.accuracy_score(y_test,predictions)

0.8292857142857143

In [19]:
rf_1=Pipeline([('tfidf',TfidfVectorizer()),('classifier',RandomForestClassifier(n_estimators=500))])

In [20]:
rf_1.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier(n_estimators=500))])

In [21]:
predict_2=rf_1.predict(X_test)

In [22]:
print(confusion_matrix(y_test,predict_2))

[[132  16   2   2 126   1  21   1   3]
 [  1 195  11   5  33   3  50   2  12]
 [  1  11 244  32   2   7  10   5  18]
 [  0   6  38 218   1   3  45   4  18]
 [  2   0   0   4 557   2   7   0   4]
 [  2   0   1   3   4 228  29  10   4]
 [  3   3   5   7   9   0 873   8  14]
 [  0   0   3   1   0   0  24 538   7]
 [  0   1   8   8   2   2  35   8 505]]


In [23]:
print(classification_report(y_test,predict_2))

                                                                              precision    recall  f1-score   support

                                                 Checking or savings account       0.94      0.43      0.59       304
                                                 Credit card or prepaid card       0.84      0.62      0.72       312
Credit reporting, credit repair services, or other personal consumer reports       0.78      0.74      0.76       330
                                                             Debt collection       0.78      0.65      0.71       333
                          Money transfer, virtual currency, or money service       0.76      0.97      0.85       576
                                                                    Mortgage       0.93      0.81      0.87       281
                                   Payday loan, title loan, or personal loan       0.80      0.95      0.87       922
                                                       

In [24]:
metrics.accuracy_score(y_test,predict_2)

0.830952380952381

In [25]:
rf_3=Pipeline([('tfidf',TfidfVectorizer()),('classifier',RandomForestClassifier(n_estimators=1000))])

In [26]:
rf_3.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('classifier', RandomForestClassifier(n_estimators=1000))])

In [27]:
X_train=vectorizer.fit_transform(X_train)

In [28]:
pip install searchgrid

Note: you may need to restart the kernel to use updated packages.


In [29]:
from sklearn.model_selection import GridSearchCV

In [30]:
param_grid={'n_estimators':[50,100,200,300]}

In [31]:
rf=RandomForestClassifier()
gridsearch=GridSearchCV(estimator=rf,param_grid=param_grid)

In [32]:
gridsearch.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'n_estimators': [50, 100, 200, 300]})

In [33]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [34]:
from xgboost import XGBClassifier

In [35]:
xgb=Pipeline([('tfidf',TfidfVectorizer()),('classifier',XGBClassifier(n_estimators=100))])

In [36]:
xgb.fit(X_train,y_train)

AttributeError: lower not found

In [ ]:
xgb_predict=xgb.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,xgb_predict))

In [ ]:
print(classification_report(y_test,xgb_predict))

In [ ]:
metrics.accuracy_score(y_test,xgb_predict)

In [ ]:
xgb_1=Pipeline([('tfidf',TfidfVectorizer()),('classifier',XGBClassifier(n_estimators=200))])

In [ ]:
xgb_1.fit(X_train,y_train)

In [ ]:
xgb_predict_1=xgb_1.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,xgb_predict_1))

In [ ]:
metrics.accuracy_score(y_test,xgb_predict_1)

In [ ]:
X_train_1=vectorizer.fit_transform(X_train)

In [ ]:
param_grid={'n_estimators':[300,500]}

In [ ]:
x=XGBClassifier()
gridsearch=GridSearchCV(estimator=x,param_grid=param_grid)

In [ ]:
gridsearch.fit(X_train_1,y_train)

In [ ]:
xgb_2=Pipeline([('tfidf',TfidfVectorizer()),('classifier',XGBClassifier(n_estimators=500))])

In [ ]:
xgb_2.fit(X_train,y_train)

In [ ]:
xgb_predict_2=xgb_2.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,xgb_predict_2))

In [ ]:
print(classification_report(y_test,xgb_predict_2))

In [ ]:
metrics.accuracy_score(y_test,xgb_predict_2)